### PR TITLE
Intent of canonical tag should be respected

### PR DESCRIPTION
**Pull request by AramZS**
These changes move to respect the canonical tag as the primary arbitrator for the question "what is my URL?". Looking at current uses across sites and social networks as well as the recommended uses from Google, the canonical tag should be considered the primary URL for any page if supplied, even over the current URL. 

@MichaelArestad Hopefully I changed this code correctly? I'm not completely sure I did. I saw there was a canonical property for `_links` that wasn't being filled and assumed it just hadn't been done yet, hopefully I was right?

### CODE REVIEW

**Comment by AramZS** [comment]
Meant to do this from a branch on my fork, sorry. >.<

**Comment by stephdau** [comment]
See comment on 0a57928

**Comment by AramZS** [comment]
@stephdau Ahh, ok. Let me adjust then.

**Comment by AramZS** [comment]
@stephdau Ok, reverted the unneeded change. Hopefully this should work as anticipated.

**Pull request merged**
